:toc:
:toc-title:
:toclevels: 3

ifdef::env-github[]
:note-caption: :information_source:
endif::[]

= [twitter] Add xcancel links to tweets

Userscript that adds "XC ↗" links to tweets, transporting you to a wonderful world free of ID verification.

== Install

=== Prerequisites

Install any userscript manager.

* Chrome:
  ** https://chromewebstore.google.com/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo[Tampermonkey]
* Firefox:
  ** https://addons.mozilla.org/en-US/firefox/addon/tampermonkey/[Tampermonkey]
  ** https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/[Greasemonkey]

=== Install from this repository

Follow this link: https://github.com/lerarosalene/open-in-xcancel/releases/latest/download/open-in-xcancel.user.js[]. Your userscript manager should trigger installation automatically.

NOTE: this option includes automatic updates. Disable them in your userscript manager if you don't want/don't trust them.

=== Build from scratch

1. Install https://nodejs.org/[NodeJS]
2. Clone this repository
3. Open terminal in cloned repository directory
4. Run `npm ci` to install dependencies
5. Run `npm run build` to build userscript
6. Grab your userscript from `dist/open-in-xcancel.user.js`, copy its contents and paste into editor in your userscript manager

NOTE: This option doesn't include automatic updates: you will need to sync your copy of repository manually and build new versions yourself.

==== Enable debug output

If for some reason you want to enable debug output, set environment variable `NODE_ENV` to `development` prior to running
`npm run build`. If you don't  know, how, you don't need debug output.

Current debug output only includes performance metric of processing a single batch of `MutationObserver` entries.

==== Customize update URL

If you want to build userscript with `@updateURL` and `@downloadURL` metadata, set environment variable `UPDATE_URL` to
desired location prior to running `npm run build`.
